### ISSUE TITLE
启用主题后500错误-Database Query Error

### ISSUE THREAD

**Issue by connyhao** [cnsamool/SaHelp-For-Typecho#1]
启用Typecho调试模式，错误如下：

Unknown column 'iconfont' in 'field list'
exception 'Typecho_Db_Query_Exception' with message 'Unknown column 'iconfont' in 'field list'' in /data/home/hyu4605230001/htdocs/var/Typecho/Db/Adapter/Mysql.php:88
Stack trace:
#0 /data/home/hyu4605230001/htdocs/var/Typecho/Db.php(354): Typecho_Db_Adapter_Mysql->query('SELECT `mid` , ...', Resource id #18, 1, 'SELECT')
#1 /data/home/hyu4605230001/htdocs/var/Typecho/Db.php(384): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /data/home/hyu4605230001/htdocs/usr/themes/SaHelp/sidebar.php(7): Typecho_Db->fetchAll(Object(Typecho_Db_Query))
#3 /data/home/hyu4605230001/htdocs/var/Widget/Archive.php(1937): require('/data/home/hyu4...')
#4 /data/home/hyu4605230001/htdocs/usr/themes/SaHelp/index.php(28): Widget_Archive->need('sidebar.php')
#5 /data/home/hyu4605230001/htdocs/var/Widget/Archive.php(2022): require_once('/data/home/hyu4...')
#6 /data/home/hyu4605230001/htdocs/var/Typecho/Router.php(138): Widget_Archive->render()
#7 /data/home/hyu4605230001/htdocs/index.php(23): Typecho_Router::dispatch()
#8 {main}

**Comment by cnsamool** [comment]
需要 启用主题前需要在typecho_metas表添加字段iconfont

ALTER TABLE typecho_metas ADD iconfont varchar(20) DEFAULT 'icon-kuaisukaishi';

还需要替换admin/manage-categories.php 分类编辑文件

**Comment by connyhao** [comment]
已按照您的描述操作，依旧错误500.

exception 'Typecho_Db_Query_Exception' in /data/home/hyu4605230001/htdocs/var/Typecho/Db/Adapter/Mysql.php:88
Stack trace:
#0 /data/home/hyu4605230001/htdocs/var/Typecho/Db.php(354): Typecho_Db_Adapter_Mysql->query('SELECT `cid` , ...', Resource id #18, 1, 'SELECT')
#1 /data/home/hyu4605230001/htdocs/var/Typecho/Db.php(384): Typecho_Db->query(Object(Typecho_Db_Query), 1)
#2 /data/home/hyu4605230001/htdocs/usr/themes/SaHelp/sidebar.php(26): Typecho_Db->fetchAll(Object(Typecho_Db_Query))
#3 /data/home/hyu4605230001/htdocs/var/Widget/Archive.php(1937): require('/data/home/hyu4...')
#4 /data/home/hyu4605230001/htdocs/usr/themes/SaHelp/index.php(28): Widget_Archive->need('sidebar.php')
#5 /data/home/hyu4605230001/htdocs/var/Widget/Archive.php(2022): require_once('/data/home/hyu4...')
#6 /data/home/hyu4605230001/htdocs/var/Typecho/Router.php(138): Widget_Archive->render()
#7 /data/home/hyu4605230001/htdocs/index.php(23): Typecho_Router::dispatch()
#8 {main}
